version: "3"

tasks:
  setup:
    desc: Initialize development setup
    deps:
      - setup-poetry
      - setup-kind

  setup-poetry:
    desc: Install dependencies
    cmds:
      - poetry install --no-root

  setup-kind:
    desc: Sets up kinds cluster
    cmds:
      - .tools/delete-cluster.sh
      - docker system prune -f -a --volumes
      - .tools/create-cluster.sh

  start-consumer:
    desc: Starts publisher service
    cmds:
      - poetry run fastapi dev services/publisher/app.py

  start-publisher:
    desc: Starts consumer service
    cmds:
      - poetry run fastapi dev services/consumer/app.py
