version: "3"

tasks:
  setup: 
    desc: Sets up kind cluster
    cmds:
      - ./tools/delete-cluster.sh
      - docker system prune -f -a --volumes
      - ./tools/create-cluster.sh

  start-consumer:
    desc: Starts publisher service
    cmds:
      - poetry run fastapi dev services/publisher/app.py

  start-publisher:
    desc: Starts consumer service
    cmds:
      - poetry run fastapi dev services/consumer/app.py