apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: consumer
          image: consumer
          ports:
            - containerPort: 3000
          env:
            - name: NATS_URL
              value: "nats://nats:4222"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  clusterIP: None
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: consumer-port