apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: publisher
          image: publisher
          ports:
            - containerPort: 3000
          env:
            - name: NATS_URL
              value: "nats://nats:4222"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  clusterIP: None
  selector:
    app: publisher
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: publisher-port